use anyhow::Result;
use fst::Map;
use lazy_static::lazy_static;
use std::{os::unix::ffi::OsStrExt, path::Path};
use thiserror::Error;

lazy_static! {
    static ref FILENAME_ICONS: Map<&'static [u8]> = {
        const FILENAME_ICONS_BYTES: &[u8] =
            include_bytes!(concat!(env!("OUT_DIR"), "/filename_icons.bin"));

        // Safety: the bytes are correctly generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe { Map::new(FILENAME_ICONS_BYTES).unwrap_unchecked() }
    };
    static ref EXT_ICONS: Map<&'static [u8]> = {
        const EXT_ICONS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/ext_icons.bin"));

        // Safety: the bytes are correctly generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe {
            Map::new(EXT_ICONS_BYTES).unwrap_unchecked()
        }
    };
    static ref FOLDER_ICONS: Map<&'static [u8]> = {
        const FOLDER_ICONS_BYTES: &[u8] =
            include_bytes!(concat!(env!("OUT_DIR"), "/folder_icons.bin"));

        // Safety: the bytes are correctly generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe { Map::new(FOLDER_ICONS_BYTES).unwrap_unchecked() }
    };
}

#[derive(Error, Debug, PartialEq)]
pub enum IconatorError {
    #[error("invalid path: {0}")]
    InvalidPath(String),
}

/// Gets the icon for a given path, first checking if the path corresponds
/// to a known filename (.babelrc.json, .gitignore, etc), then checking if the path corresponds to a known extension.
/// Returns None if no icon is found.
pub fn get_icon_for_file(path: impl AsRef<Path>) -> Result<Option<u64>, IconatorError> {
    let path = path.as_ref();
    let basename = path
        .file_name()
        .ok_or_else(|| IconatorError::InvalidPath(path.to_string_lossy().into_owned()))?;

    if let Some(icon) = FILENAME_ICONS.get(basename.as_bytes()) {
        return Ok(Some(icon));
    }

    let ext = path
        .extension()
        .ok_or_else(|| IconatorError::InvalidPath("path does not have an extension".to_string()))?;

    Ok(EXT_ICONS.get(ext.as_bytes()))
}

/// Gets the icon for a given folder name checking if its path corresponds
/// to a known folder name.
/// Returns None if no icon is found.
pub fn get_icon_for_folder(path: impl AsRef<Path>) -> Result<Option<u64>, IconatorError> {
    let path = path.as_ref();
    let basename = path
        .file_name()
        .ok_or_else(|| IconatorError::InvalidPath(path.to_string_lossy().into_owned()))?;

    Ok(FOLDER_ICONS.get(basename.as_bytes()))
}

// TODO: add tests that are not happy path
#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn my_test() {
        assert_eq!(get_icon_for_file("dfglkjdf.."), Ok(Some(617)));
    }

    #[test]
    fn common_languages() {
        assert_eq!(get_icon_for_file("./test.js"), Ok(Some(296)));
        assert_eq!(get_icon_for_file("./test.ts"), Ok(Some(633)));
        assert_eq!(get_icon_for_file("./test.jsx"), Ok(Some(508)));
        assert_eq!(get_icon_for_file("./test.tsx"), Ok(Some(529)));
        assert_eq!(get_icon_for_file("./test.json"), Ok(Some(284)));
        assert_eq!(get_icon_for_file("./test.yaml"), Ok(Some(708)));
        assert_eq!(get_icon_for_file("./test.yml"), Ok(Some(708)));
        assert_eq!(get_icon_for_file("./test.md"), Ok(Some(361)));
        assert_eq!(get_icon_for_file("./test.css"), Ok(Some(116)));
        assert_eq!(get_icon_for_file("./test.html"), Ok(Some(255)));
        assert_eq!(get_icon_for_file("./test.rs"), Ok(Some(525)));
    }

    #[test]
    fn common_folders() {
        assert_eq!(get_icon_for_folder("./.github"), Ok(Some(862)));
        assert_eq!(get_icon_for_folder("./src"), Ok(Some(1054)));
        assert_eq!(get_icon_for_folder("./tests"), Ok(Some(1084)));
    }
}
